baseurl: ""
markdown: redcarpet
redcarpet:
    extensions: [tables]
safe: false
pygments: true
excerpt_separator: "\n\n\n"
paginate: 5
sitemapurl: "http://hpsoar.github.io"

gems:
  - jemoji
  - jekyll-mentions
